const questionsAndAnswers = {
    'In which country did the dish paella originate?': 'Spain',
    'Which country is known as the Land of the Rising Sun?': 'Japan',
    'Which animal is known as the "Ship of the Desert"?': 'Camel',
    'Name the National animal of India?': 'Tiger',
    'Name the place known as the Roof of the World?': 'Tibet',
    'Name the longest river on the Earth?': 'Nile',
    'Name the smallest continent?': 'Australia',
    'Which is the principal source of energy for the Earth?': 'Sun',
    'Which festival is known as the festival of light?': 'Diwali',
    'Name a bird that lays the largest eggs?': 'Ostrich',
    'Name the planet known as the Red Planet?': 'Mars',
    'Name a natural satellite of Earth?': 'Moon',
    'What is the national bird of the United States?': 'Eagle',
    'What language is spoken in Brazil?': 'Portuguese',
    'What is the capital city of Canada?': 'Ottawa',
    'What is the capital city of Spain?': 'Madrid',
    'What is the primary ingredient in guacamole?': 'Avocado',
    'Which fruit is the most popular and consumed worldwide?': 'Tomato',
    'In which country is the Sphinx located?': 'Egypt',
    'What is the only mammal capable of sustained flight?': 'Bat',
    'Which bird is known for its ability to mimic human speech?': 'Parrot',
    'What is the name of the Italian dish made of thinly sliced raw meat or fish, typically served as an appetizer?': 'Carpaccio',
    'In which country did the sandwich originate?': 'England',
    'What is the largest country in South America by land area?': 'Brazil',
    'Which country is known as the Land of the Midnight Sun?': 'Norway',
};
export default questionsAndAnswers;